language: go

services:
  - docker

go:
  - 1.x

script:
  - go test -v ./...
  - docker build -t dimshimdim/cicd-2 .

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master

doploy:
  provider: script
  script: bash .heroku_deploy
  on:
    branch: master
